Upgrade dependencies to fix broken jobs (#127)
dev dependencies are too old, and now it reported error in unrelated
PRs.
Let's upgrade them. Current issue is fixed by this change.



<details>

<summary>Failure log: </summary>

```
Prepare all required actions
Run ./line-openapi/.github/actions/post-comment-action
Run pwd
/home/runner/work/line-openapi/line-openapi
Run npm ci

added 29 packages, and audited 30 packages in 1s

7 vulnerabilities (6 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
Run node /home/runner/work/line-openapi/line-openapi/./line-openapi/.github/actions/post-comment-action/main.js
RequestError [HttpError]: Invalid response body while trying to fetch https://api.github.com/repos/line/line-openapi/issues/126/comments: Premature close
    at /home/runner/work/line-openapi/line-openapi/line-openapi/.github/actions/post-comment-action/node_modules/@octokit/request/dist-node/index.js:108:11
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async run (/home/runner/work/line-openapi/line-openapi/line-openapi/.github/actions/post-comment-action/main.js:21:30) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/line/line-openapi/issues/126/comments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/22',
      authorization: 'bearer [REDACTED]'
    },
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }
}
Error: Error in this script: Invalid response body while trying to fetch https://api.github.com/repos/line/line-openapi/issues/126/comments: Premature close
Error: Process completed with exit code 1.
```
</details>