Fix CI issues related to zx (#67)
This change resolves https://github.com/line/line-openapi/issues/66.
```
npm install -g zx
```
failed due to permission issue
(log)
```
Run npm install -g zx
npm error code EACCES
npm error syscall symlink
npm error path ../../../lib/node_modules/zx/man/zx.1
npm error dest /usr/local/share/man/man1/zx.1
npm error errno -13
npm error [Error: EACCES: permission denied, symlink '../../../lib/node_modules/zx/man/zx.1' -> '/usr/local/share/man/man1/zx.1'] {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'symlink',
npm error   path: '../../../lib/node_modules/zx/man/zx.1',
npm error   dest: '/usr/local/share/man/man1/zx.1'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.

npm error A complete log of this run can be found in: /home/runner/.npm/_logs/202[4](https://github.com/line/line-openapi/actions/runs/10552186284/job/29230645454?pr=65#step:4:5)-08-26T01_57_10_003Z-debug-0.log
Error: Process completed with exit code 243.
```